### ISSUE TITLE
Opting into the Segment Heap on Windows improves analysis speed by ~20%

### ISSUE THREAD

**Issue by gaasedelen** [Vector35/binaryninja-api#2778]
**Is your feature request related to a problem? Please describe.**

The 'legacy' NT Heap which Binary Ninja uses on Windows is notably slow. _Opting in to the 'newer' Segment Heap which was added in the Windows 8 era appears to improve Binary Ninja analysis speed in excess of 20%._

These gains should be seen on at least Windows 8/10/11

**Describe the solution you'd like**

Binary Ninja should opt-in to use the Windows Segment Heap by setting the following registry key upon install:

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\binaryninja.exe]
"FrontEndHeapDebugOptions"=dword:00000008
```

It is recommended you reboot after toggling this key on or off, to ensure its effects kick in.

More details: https://www.blackhat.com/docs/us-16/materials/us-16-Yason-Windows-10-Segment-Heap-Internals-wp.pdf

**Describe alternatives you've considered**

N / A

**Additional context**

Sample runs from dev branch on a Windows 8.1 x64 VM with 4 cores:

```
NTOS:
  Before: Analysis update took 1398.097 seconds
   After: Analysis update took 1121.882 seconds

JScript:
  Before: Analysis update took 139.466 seconds
   After: Analysis update took 113.748 seconds
```

These reflect a 20-25% improvement on analysis times.

Sample binaries / test cases for convenience:

[jscript9.zip](https://github.com/Vector35/binaryninja-api/files/7700378/jscript9.zip)
[ntkrnlmp.zip](https://github.com/Vector35/binaryninja-api/files/7700379/ntkrnlmp.zip)

---

Supposedly Python 2 would not play nice with Segment Heap, but since that is no longer supported by Binary Ninja you should be free to enable this. I haven't noticed any regressions, but YMMV.
